# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: holistic_landmarks.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import kinect_pose_landmarks_pb2 as kinect__pose__landmarks__pb2
from . import mediapipe_pose_landmarks_pb2 as mediapipe__pose__landmarks__pb2
from . import hand_landmarks_pb2 as hand__landmarks__pb2
from . import face_results_pb2 as face__results__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18holistic_landmarks.proto\x12\x0ehumanLandmarks\x1a\x1bkinect_pose_landmarks.proto\x1a\x1emediapipe_pose_landmarks.proto\x1a\x14hand_landmarks.proto\x1a\x12\x66\x61\x63\x65_results.proto\"\xd9\x02\n\x11HolisticLandmarks\x12\x42\n\x13kinectPoseLandmarks\x18\x01 \x01(\x0b\x32#.humanLandmarks.KinectPoseLandmarksH\x00\x12H\n\x16mediaPipePoseLandmarks\x18\x05 \x01(\x0b\x32&.humanLandmarks.MediaPipePoseLandmarksH\x00\x12\x38\n\x11leftHandLandmarks\x18\x02 \x01(\x0b\x32\x1d.humanLandmarks.HandLandmarks\x12\x39\n\x12rightHandLandmarks\x18\x03 \x01(\x0b\x32\x1d.humanLandmarks.HandLandmarks\x12\x30\n\x0b\x66\x61\x63\x65Results\x18\x04 \x01(\x0b\x32\x1b.humanLandmarks.FaceResultsB\x0f\n\rposeLandmarksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'holistic_landmarks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HOLISTICLANDMARKS']._serialized_start=148
  _globals['_HOLISTICLANDMARKS']._serialized_end=493
# @@protoc_insertion_point(module_scope)

