# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hand_landmarks.proto
# Protobuf Python Version: 4.25.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_generated.landmark_pb2 as landmark__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14hand_landmarks.proto\x12\x0ehumanLandmarks\x1a\x0elandmark.proto\"\xc4\x03\n\rHandLandmarks\x12+\n\tlandmarks\x18\x01 \x03(\x0b\x32\x18.humanLandmarks.Landmark\"\x85\x03\n\rLandmarkIndex\x12\t\n\x05wrist\x10\x00\x12\x0c\n\x08thumbCMC\x10\x01\x12\x0c\n\x08thumbMCP\x10\x02\x12\x0b\n\x07thumbIP\x10\x03\x12\x0c\n\x08thumbTIP\x10\x04\x12\x12\n\x0eindexFingerMCP\x10\x05\x12\x12\n\x0eindexFingerPIP\x10\x06\x12\x12\n\x0eindexFingerDIP\x10\x07\x12\x12\n\x0eindexFingerTIP\x10\x08\x12\x13\n\x0fmiddleFingerMCP\x10\t\x12\x13\n\x0fmiddleFingerPIP\x10\n\x12\x13\n\x0fmiddleFingerDIP\x10\x0b\x12\x13\n\x0fmiddleFingerTIP\x10\x0c\x12\x11\n\rringFingerMCP\x10\r\x12\x11\n\rringFingerPIP\x10\x0e\x12\x11\n\rringFingerDIP\x10\x0f\x12\x11\n\rringFingerTIP\x10\x10\x12\x0c\n\x08pinkyMCP\x10\x11\x12\x0c\n\x08pinkyPIP\x10\x12\x12\x0c\n\x08pinkyDIP\x10\x13\x12\x0c\n\x08pinkyTIP\x10\x14\x12\n\n\x06length\x10\x15\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hand_landmarks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDLANDMARKS']._serialized_start=57
  _globals['_HANDLANDMARKS']._serialized_end=509
  _globals['_HANDLANDMARKS_LANDMARKINDEX']._serialized_start=120
  _globals['_HANDLANDMARKS_LANDMARKINDEX']._serialized_end=509
# @@protoc_insertion_point(module_scope)
