# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inferencer_control.proto
# Protobuf Python Version: 4.25.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18inferencer_control.proto\x12\x17violetmarionette.shared\"\x07\n\x05\x45mpty\"\'\n\x0f\x43\x61meraSelection\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\x05\"!\n\x0ePreviewSetting\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"b\n\x1dLandmarkVisualizationSettings\x12\x14\n\x0cpose_enabled\x18\x01 \x01(\x08\x12\x15\n\rhands_enabled\x18\x02 \x01(\x08\x12\x14\n\x0c\x66\x61\x63\x65_enabled\x18\x03 \x01(\x08\"9\n\x0fOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\xb6\x01\n\x10\x45stimationStatus\x12\x12\n\nis_running\x18\x01 \x01(\x08\x12\x1d\n\x15selected_camera_index\x18\x02 \x01(\x05\x12\x17\n\x0fpreview_enabled\x18\x03 \x01(\x08\x12V\n\x16landmark_visualization\x18\x04 \x01(\x0b\x32\x36.violetmarionette.shared.LandmarkVisualizationSettings2\xda\x04\n\x11\x45stimationControl\x12\x62\n\x0cSelectCamera\x12(.violetmarionette.shared.CameraSelection\x1a(.violetmarionette.shared.OperationResult\x12\x66\n\x11SetPreviewEnabled\x12\'.violetmarionette.shared.PreviewSetting\x1a(.violetmarionette.shared.OperationResult\x12|\n\x18SetLandmarkVisualization\x12\x36.violetmarionette.shared.LandmarkVisualizationSettings\x1a(.violetmarionette.shared.OperationResult\x12V\n\tGetStatus\x12\x1e.violetmarionette.shared.Empty\x1a).violetmarionette.shared.EstimationStatus\x12Q\n\x05Start\x12\x1e.violetmarionette.shared.Empty\x1a(.violetmarionette.shared.OperationResult\x12P\n\x04Stop\x12\x1e.violetmarionette.shared.Empty\x1a(.violetmarionette.shared.OperationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inferencer_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=53
  _globals['_EMPTY']._serialized_end=60
  _globals['_CAMERASELECTION']._serialized_start=62
  _globals['_CAMERASELECTION']._serialized_end=101
  _globals['_PREVIEWSETTING']._serialized_start=103
  _globals['_PREVIEWSETTING']._serialized_end=136
  _globals['_LANDMARKVISUALIZATIONSETTINGS']._serialized_start=138
  _globals['_LANDMARKVISUALIZATIONSETTINGS']._serialized_end=236
  _globals['_OPERATIONRESULT']._serialized_start=238
  _globals['_OPERATIONRESULT']._serialized_end=295
  _globals['_ESTIMATIONSTATUS']._serialized_start=298
  _globals['_ESTIMATIONSTATUS']._serialized_end=480
  _globals['_ESTIMATIONCONTROL']._serialized_start=483
  _globals['_ESTIMATIONCONTROL']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
