# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import inferencer_control_pb2 as inferencer__control__pb2


class EstimationControlStub(object):
    """Pose estimation control service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelectCamera = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/SelectCamera',
                request_serializer=inferencer__control__pb2.CameraSelection.SerializeToString,
                response_deserializer=inferencer__control__pb2.OperationResult.FromString,
                )
        self.SetPreviewEnabled = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/SetPreviewEnabled',
                request_serializer=inferencer__control__pb2.PreviewSetting.SerializeToString,
                response_deserializer=inferencer__control__pb2.OperationResult.FromString,
                )
        self.SetLandmarkVisualization = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/SetLandmarkVisualization',
                request_serializer=inferencer__control__pb2.LandmarkVisualizationSettings.SerializeToString,
                response_deserializer=inferencer__control__pb2.OperationResult.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/GetStatus',
                request_serializer=inferencer__control__pb2.Empty.SerializeToString,
                response_deserializer=inferencer__control__pb2.EstimationStatus.FromString,
                )
        self.Start = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/Start',
                request_serializer=inferencer__control__pb2.Empty.SerializeToString,
                response_deserializer=inferencer__control__pb2.OperationResult.FromString,
                )
        self.Stop = channel.unary_unary(
                '/violetmarionette.shared.EstimationControl/Stop',
                request_serializer=inferencer__control__pb2.Empty.SerializeToString,
                response_deserializer=inferencer__control__pb2.OperationResult.FromString,
                )


class EstimationControlServicer(object):
    """Pose estimation control service
    """

    def SelectCamera(self, request, context):
        """Select camera to use
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreviewEnabled(self, request, context):
        """Enable/disable preview (shared memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLandmarkVisualization(self, request, context):
        """Set landmark visualization settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start estimation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop estimation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimationControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelectCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectCamera,
                    request_deserializer=inferencer__control__pb2.CameraSelection.FromString,
                    response_serializer=inferencer__control__pb2.OperationResult.SerializeToString,
            ),
            'SetPreviewEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreviewEnabled,
                    request_deserializer=inferencer__control__pb2.PreviewSetting.FromString,
                    response_serializer=inferencer__control__pb2.OperationResult.SerializeToString,
            ),
            'SetLandmarkVisualization': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLandmarkVisualization,
                    request_deserializer=inferencer__control__pb2.LandmarkVisualizationSettings.FromString,
                    response_serializer=inferencer__control__pb2.OperationResult.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=inferencer__control__pb2.Empty.FromString,
                    response_serializer=inferencer__control__pb2.EstimationStatus.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=inferencer__control__pb2.Empty.FromString,
                    response_serializer=inferencer__control__pb2.OperationResult.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=inferencer__control__pb2.Empty.FromString,
                    response_serializer=inferencer__control__pb2.OperationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'violetmarionette.shared.EstimationControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EstimationControl(object):
    """Pose estimation control service
    """

    @staticmethod
    def SelectCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/SelectCamera',
            inferencer__control__pb2.CameraSelection.SerializeToString,
            inferencer__control__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPreviewEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/SetPreviewEnabled',
            inferencer__control__pb2.PreviewSetting.SerializeToString,
            inferencer__control__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLandmarkVisualization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/SetLandmarkVisualization',
            inferencer__control__pb2.LandmarkVisualizationSettings.SerializeToString,
            inferencer__control__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/GetStatus',
            inferencer__control__pb2.Empty.SerializeToString,
            inferencer__control__pb2.EstimationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/Start',
            inferencer__control__pb2.Empty.SerializeToString,
            inferencer__control__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/violetmarionette.shared.EstimationControl/Stop',
            inferencer__control__pb2.Empty.SerializeToString,
            inferencer__control__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
