# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kinect_pose_landmarks.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_generated.landmark_pb2 as landmark__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkinect_pose_landmarks.proto\x12\x0ehumanLandmarks\x1a\x0elandmark.proto\"\xd7\x04\n\x13KinectPoseLandmarks\x12+\n\tlandmarks\x18\x01 \x03(\x0b\x32\x18.humanLandmarks.Landmark\"\x92\x04\n\rLandmarkIndex\x12\n\n\x06PELVIS\x10\x00\x12\x0f\n\x0bSPINE_NAVAL\x10\x01\x12\x0f\n\x0bSPINE_CHEST\x10\x02\x12\x08\n\x04NECK\x10\x03\x12\x11\n\rCLAVICLE_LEFT\x10\x04\x12\x11\n\rSHOULDER_LEFT\x10\x05\x12\x0e\n\nELBOW_LEFT\x10\x06\x12\x0e\n\nWRIST_LEFT\x10\x07\x12\r\n\tHAND_LEFT\x10\x08\x12\x10\n\x0cHANDTIP_LEFT\x10\t\x12\x0e\n\nTHUMB_LEFT\x10\n\x12\x12\n\x0e\x43LAVICLE_RIGHT\x10\x0b\x12\x12\n\x0eSHOULDER_RIGHT\x10\x0c\x12\x0f\n\x0b\x45LBOW_RIGHT\x10\r\x12\x0f\n\x0bWRIST_RIGHT\x10\x0e\x12\x0e\n\nHAND_RIGHT\x10\x0f\x12\x11\n\rHANDTIP_RIGHT\x10\x10\x12\x0f\n\x0bTHUMB_RIGHT\x10\x11\x12\x0c\n\x08HIP_LEFT\x10\x12\x12\r\n\tKNEE_LEFT\x10\x13\x12\x0e\n\nANKLE_LEFT\x10\x14\x12\r\n\tFOOT_LEFT\x10\x15\x12\r\n\tHIP_RIGHT\x10\x16\x12\x0e\n\nKNEE_RIGHT\x10\x17\x12\x0f\n\x0b\x41NKLE_RIGHT\x10\x18\x12\x0e\n\nFOOT_RIGHT\x10\x19\x12\x08\n\x04HEAD\x10\x1a\x12\x08\n\x04NOSE\x10\x1b\x12\x0c\n\x08\x45YE_LEFT\x10\x1c\x12\x0c\n\x08\x45\x41R_LEFT\x10\x1d\x12\r\n\tEYE_RIGHT\x10\x1e\x12\r\n\tEAR_RIGHT\x10\x1f\x12\n\n\x06LENGTH\x10 b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kinect_pose_landmarks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KINECTPOSELANDMARKS']._serialized_start=64
  _globals['_KINECTPOSELANDMARKS']._serialized_end=663
  _globals['_KINECTPOSELANDMARKS_LANDMARKINDEX']._serialized_start=133
  _globals['_KINECTPOSELANDMARKS_LANDMARKINDEX']._serialized_end=663
# @@protoc_insertion_point(module_scope)
