# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe_pose_landmarks.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import landmark_pb2 as landmark__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emediapipe_pose_landmarks.proto\x12\x0ehumanLandmarks\x1a\x0elandmark.proto\"\xec\x04\n\x16MediaPipePoseLandmarks\x12\x30\n\tlandmarks\x18\x01 \x03(\x0b\x32\x1d.humanLandmarks.LandmarkPoint\"\x9f\x04\n\rLandmarkIndex\x12\x08\n\x04nose\x10\x00\x12\x10\n\x0cleftEyeInner\x10\x01\x12\x0b\n\x07leftEye\x10\x02\x12\x10\n\x0cleftEyeOuter\x10\x03\x12\x11\n\rrightEyeInner\x10\x04\x12\x0c\n\x08rightEye\x10\x05\x12\x11\n\rrightEyeOuter\x10\x06\x12\x0b\n\x07leftEar\x10\x07\x12\x0c\n\x08rightEar\x10\x08\x12\r\n\tmouthLeft\x10\t\x12\x0e\n\nmouthRight\x10\n\x12\x10\n\x0cleftShoulder\x10\x0b\x12\x11\n\rrightShoulder\x10\x0c\x12\r\n\tleftElbow\x10\r\x12\x0e\n\nrightElbow\x10\x0e\x12\r\n\tleftWrist\x10\x0f\x12\x0e\n\nrightWrist\x10\x10\x12\r\n\tleftPinky\x10\x11\x12\x0e\n\nrightPinky\x10\x12\x12\r\n\tleftIndex\x10\x13\x12\x0e\n\nrightIndex\x10\x14\x12\r\n\tleftThumb\x10\x15\x12\x0e\n\nrightThumb\x10\x16\x12\x0b\n\x07leftHip\x10\x17\x12\x0c\n\x08rightHip\x10\x18\x12\x0c\n\x08leftKnee\x10\x19\x12\r\n\trightKnee\x10\x1a\x12\r\n\tleftAnkle\x10\x1b\x12\x0e\n\nrightAnkle\x10\x1c\x12\x0c\n\x08leftHeel\x10\x1d\x12\r\n\trightHeel\x10\x1e\x12\x11\n\rleftFootIndex\x10\x1f\x12\x12\n\x0erightFootIndex\x10 \x12\n\n\x06length\x10!b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe_pose_landmarks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MEDIAPIPEPOSELANDMARKS']._serialized_start=67
  _globals['_MEDIAPIPEPOSELANDMARKS']._serialized_end=687
  _globals['_MEDIAPIPEPOSELANDMARKS_LANDMARKINDEX']._serialized_start=144
  _globals['_MEDIAPIPEPOSELANDMARKS_LANDMARKINDEX']._serialized_end=687
# @@protoc_insertion_point(module_scope)

